### ISSUE TITLE
ANSI escapes for clear screen

### ISSUE THREAD

**Issue by j0ng4b** [alpin111/rainfall#1]
https://github.com/alpin111/rainfall/blob/758be607f8830b7a5bf3a843848e052681497eef/source/rainfall.py#L25-L30

As far as I know there are a [ANSI escape sequence for clear the screen](https://gist.github.com/fnky/458719343aabd01cfb17a3a4f7296797#erase-functions), so this lines can be replaced for that sequence.

**Comment by k-blo** [comment]
Thanks, you are right. The new version uses an ANSI escape sequence.
