### ISSUE TITLE
Python Shebang

### ISSUE THREAD

**Issue by Neurognostic** [alpin111/rainfall#4]
Is there a reason [the shebang](https://github.com/alpin111/rainfall/blob/d502e0409981b2f2e428296bebf8508f9ccb04b0/source/rainfall.py#L1) is referring to `python3.10` specifically rather than just `python3`?

Arch Linux doesn't provide `python3.10` anymore and changing the shebang to `python3` appears to work fine.

```patch
diff --git i/source/rainfall.py w/source/rainfall.py
index a2d8194..268ade0 100755
--- i/source/rainfall.py
+++ w/source/rainfall.py
@@ -1,4 +1,4 @@
-#!/usr/bin/env python3.10
+#!/usr/bin/env python3
 # -*- coding: utf-8 -*-
 
 import time
```

**Comment by k-blo** [comment]
Thanks for pointing that out @Neurognostic 
The source has been updated and the Arch package maintainer notified.
Feel free to bump this issue if the maintainer doesn't update the package or orphan/adopt the package yourself.

**Comment by Neurognostic** [comment]
I ended up adopting the package switching it to using your tarball release and made you a co-maintainer.
